# -*- coding: utf-8 -*-
"""CV lab 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19FkZ_xzXofs5yMSzAtW9K1ZzBcF5TqN2
"""

import cv2
import numpy as np
from matplotlib import pyplot as plt

img=cv2.imread("/content/Nature view.jpg",cv2.IMREAD_GRAYSCALE)

display(img)

if img is None:
  print("error: image not found.")
else:
  plt.figure(figsize=(12,10))
  plt.subplot(3,3,1)
  plt.imshow(img,cmap="gray")
  plt.title("original image")
  plt.axis("off")
  for i in range(8):

    bit_plane=(img>>i)&1
    vis_plane=bit_plane*255
    plt.subplot(3,3,i+2)
    plt.imshow(vis_plane,cmap="gray")
    plt.title("bit plane {i}")
    plt.axis("off")
plt.tight_layout()

import cv2
import numpy as np
import matplotlib.pyplot as plt

# Read grayscale image
img = cv2.imread("/content/Nature view.jpg", 0)

if img is None:
    print("Error: Image not found")
else:
    plt.figure(figsize=(12, 10))

    # Original Image
    plt.subplot(3, 3, 1)
    plt.imshow(img, cmap='gray')
    plt.title("Original Image")
    plt.axis('off')

    rows, cols = img.shape

    # Extract each bit plane manually
    for k in range(8):
        bit_plane = np.zeros((rows, cols), dtype=np.uint8)

        for i in range(rows):
            for j in range(cols):
                pixel = img[i, j]

                # Extract kth bit manually
                bit = (pixel // (2 ** k)) % 2

                if bit == 1:
                    bit_plane[i, j] = 255
                else:
                    bit_plane[i, j] = 0

        plt.subplot(3, 3, k + 2)
        plt.imshow(bit_plane, cmap='gray')
        plt.title(f"Bit Plane {k}")
        plt.axis('off')

    plt.tight_layout()
    plt.show()